// samples/react-app/src/GoodApp.jsx
// Corrected version of App.jsx — same page, every intentional violation fixed.
// Serve at /good.html to see the a11y-sdk audit/behave scripts pass cleanly.

export default function GoodApp() {
  return (
    <div>
      <a href="#main-content" className="skip-link">
        Skip to main content
      </a>

      <nav aria-label="Primary">
        <a href="/good.html" aria-current="page">
          Home
        </a>{" "}
        <a href="/catalog">Catalog</a>
      </nav>

      <main id="main-content">
        <h1>Welcome to the shop</h1>

        <img src="https://placehold.co/200x150" alt="Wireless headphones on a white background" />

        <p>
          See our offers — <a href="/offers">view this week's offers</a>
        </p>

        <h2>Featured Deals</h2>

        <form>
          <div>
            <label htmlFor="search">Search products</label>
            <input id="search" type="text" />
          </div>

          <fieldset>
            <legend>Shipping method</legend>
            <input type="radio" name="shipping" id="ship-standard" value="standard" />
            <label htmlFor="ship-standard">Standard</label>
            <input type="radio" name="shipping" id="ship-express" value="express" />
            <label htmlFor="ship-express">Express</label>
          </fieldset>

          <div>
            <label htmlFor="email">Email</label>
            <input
              id="email"
              type="email"
              autoComplete="email"
              aria-invalid="true"
              aria-describedby="email-error"
            />
            <p id="email-error">Enter a valid email address</p>
          </div>
        </form>

        <button aria-label="Search" onClick={() => console.log("search")}>
          🔍
        </button>

        <button onClick={() => console.log("add to cart")}>Add to cart</button>

        <ul>
          <li>Product A — $10</li>
          <li>Product B — $20</li>
        </ul>
      </main>
    </div>
  );
}

// samples/vue-app/src/GoodApp.vue
<template>
  <!-- Corrected version of App.vue — same page, every intentional violation
       fixed. Serve at /good.html to see the a11y-sdk audit/behave scripts
       pass cleanly. -->
  <div>
    <a href="#main-content" class="skip-link">Przejdź do treści głównej</a>

    <nav aria-label="Primary">
      <a href="/good.html" aria-current="page">Strona główna</a>
      <a href="/katalog">Katalog</a>
    </nav>

    <main id="main-content">
      <h1>Nasze oferty</h1>

      <img src="https://placehold.co/200x150" alt="Słuchawki bezprzewodowe na białym tle" />

      <p>Sprawdź promocje — <a href="/promocje">zobacz oferty tego tygodnia</a></p>

      <h2>Wyróżnione oferty</h2>

      <form>
        <div>
          <label for="email">
            Twój e-mail
            <input id="email" type="email" autocomplete="email" />
          </label>
        </div>

        <fieldset>
          <legend>Sposób dostawy</legend>
          <label for="dostawa-standard">
            <input type="radio" name="dostawa" id="dostawa-standard" value="standard" />
            Standardowa
          </label>
          <label for="dostawa-ekspres">
            <input type="radio" name="dostawa" id="dostawa-ekspres" value="ekspres" />
            Ekspresowa
          </label>
        </fieldset>

        <div>
          <label for="promo-code">
            Kod promocyjny
            <input
              id="promo-code"
              type="text"
              aria-invalid="true"
              aria-describedby="promo-code-error"
            />
          </label>
          <p id="promo-code-error">Ten kod wygasł</p>
        </div>
      </form>

      <button aria-label="Subskrybuj" @click="subscribe">✉️</button>

      <button @click="dismiss">Zamknij powiadomienie</button>

      <ul>
        <li>Oferta A — 49 zł</li>
        <li>Oferta B — 99 zł</li>
      </ul>
    </main>
  </div>
</template>

<script setup>
function subscribe() {}
function dismiss() {}
</script>
